Fixup image generation scripts
Scripts should now work from the top of the OpenWRT build tree,
and no longer rely on /home/atlas/openwrt

Signed-off-by: Michel Stam <mstam@ripe.net>

diff --git a/atlas_extra_v3/initprobe/pimage b/atlas_extra_v3/initprobe/pimage
--- a/atlas_extra_v3/initprobe/pimage
+++ b/atlas_extra_v3/initprobe/pimage
@@ -3,21 +3,52 @@ export probe_env=$1
 
 model="tl-mr3020"
 
-cwd=$PWD
-basedir=$cwd/$(dirname "$0")
-cd "$basedir"
+OPENWRT=${PWD}
+basedir=${OPENWRT}/$(dirname "$0")
 
-"$basedir"/add_atlas
-
-BINDIR=/home/atlas/openwrt/bin/ar71xx
-FIRMWARE_APPS_VERSION_FILE=/tmp/root/home/atlas/state/FIRMWARE_APPS_VERSION
-FIRMWARE_APPS_VERSION=`cat $FIRMWARE_APPS_VERSION_FILE`
-ROOTFS_VERSION="$FIRMWARE_APPS_VERSION"
-LOC_ROOTFS_FILE="rootfs-$ROOTFS_VERSION.img.bz2"
-ROOTFS_FILE="rootfs-$model-$ROOTFS_VERSION.img.bz2"
+BINDIR=${OPENWRT}/bin/ar71xx
+ATLASROOT=${BINDIR}/openwrt-ar71xx-atlas-rootfs.tar
 OPENSSL=openssl
 BASE64=base64
 KEYDIR=$HOME/atlas-signing-keys
+
+if [ ! -d "${KEYDIR}" ]; then
+	echo 'Please setup ${KEYDIR}'
+	exit 1
+fi
+
+for NEEDED in include package tools scripts target toolchain; do
+	if [ ! -d "${OPENWRT}/${NEEDED}" ]; then
+		echo 'Please execute from an OpenWRT v3 directory'
+		exit 1
+	fi
+done
+
+if ( [ ! -d "${OPENWRT}/build_dir" ] ||
+     [ ! -d "${OPENWRT}/staging_dir" ] ||
+     [ ! -d "${BINDIR}" ] ||
+     [ ! -f "${ATLASROOT}" ] ); then
+	echo 'Please execute from a built OpenWRT v3 directory'
+	exit 1
+fi
+
+case "${probe_env}" in
+	prod|test|dev)
+		;;
+
+	*)
+		echo 'Please specify environment'
+		exit 1
+		;;
+esac
+
+"$basedir"/add_atlas || exit 1
+cd "$basedir"
+
+FIRMWARE_APPS_VERSION=$(tar Oxvf ${ATLASROOT} ./home/atlas/state/FIRMWARE_APPS_VERSION)
+ROOTFS_VERSION="$FIRMWARE_APPS_VERSION"
+LOC_ROOTFS_FILE="rootfs-$ROOTFS_VERSION.img.bz2"
+ROOTFS_FILE="rootfs-$model-$ROOTFS_VERSION.img.bz2"
 
 if [ $probe_env = "prod" ] ; then
 	PREF=""
@@ -38,6 +69,15 @@ fi
 
 #exit
 
-scp $BINDIR/$LOC_ROOTFS_FILE atlas@admin$PREF:$ROOTFS_FILE
+scp $BINDIR/$LOC_ROOTFS_FILE atlas@admin$PREF:$ROOTFS_FILE >/dev/null 2>&1
+copyres=$?
+if [ $copyres -ne 0 ]; then
+	echo "Cannot automatically install firmware on atlas@admin$PREF. Please:"
+	echo "- Copy $BINDIR/$LOC_ROOTFS_FILE to atlas@admin$PREF:$ROOTFS_FILE"
+	echo -n "- Execute on atlas@admin$PREF "
+fi
+
 printf  "./atlas/manage.py import_app -a $model -w $ROOTFS_VERSION -g md5 -f ./$ROOTFS_FILE $sigarg\n"
-ssh atlas@admin$PREF "./atlas/manage.py import_app -a $model -w $ROOTFS_VERSION -g md5 -f ./$ROOTFS_FILE $sigarg"
+if [ $copyres -eq 0 ]; then
+	ssh atlas@admin$PREF "./atlas/manage.py import_app -a $model -w $ROOTFS_VERSION -g md5 -f ./$ROOTFS_FILE $sigarg"
+fi
diff --git a/atlas_extra_v5/initprobe/pimage b/atlas_extra_v5/initprobe/pimage
--- a/atlas_extra_v5/initprobe/pimage
+++ b/atlas_extra_v5/initprobe/pimage
@@ -10,34 +10,56 @@ export probe_env=$1
 
 model="atlas-mox"
 
-cwd=$PWD
-basedir=$cwd/$(dirname "$0")
+OPENWRT=$PWD
+basedir=${OPENWRT}/$(dirname "$0")
+
+BINDIR=${OPENWRT}/bin/targets/mvebu/cortexa53
+OPENSSL=openssl
+BASE64=base64
+KEYDIR=$HOME/atlas-signing-keys
+
+if [ ! -d "${KEYDIR}" ]; then
+	echo 'Please setup ${KEYDIR}'
+	exit 1
+fi
+
+for NEEDED in include package tools scripts target toolchain; do
+	if [ ! -d "${OPENWRT}/${NEEDED}" ]; then
+		echo 'Please execute from an OpenWRT v5 directory'
+		exit 1
+	fi
+done
+
+if ( [ ! -d "${OPENWRT}/build_dir" ] ||
+     [ ! -d "${OPENWRT}/staging_dir" ] ||
+     [ ! -d "${BINDIR}" ] ||
+     [ ! -f "${ATLASROOT}" ] ); then
+	echo 'Please execute from a built OpenWRT v5 directory'
+	exit 1
+fi
+
+case "${probe_env}" in
+	prod|test|dev)
+		;;
+
+	*)
+		echo 'Please specify environment'
+		exit 1
+		;;
+esac
+
 cd "$basedir"
 
-get_version()
-{
-	(
-		mkdir -p /tmp/root
-		cd /tmp/root
-		tar xvzf "$BINDIR/$LOC_ROOTFS_FILE_GZ" "$FIRMWARE_FILE" >/dev/null
-		cat "$FIRMWARE_FILE"
-	)
-}
-
-BINDIR=$cwd/bin/targets/mvebu/cortexa53
-FIRMWARE_FILE=./home/atlas/state/FIRMWARE_APPS_VERSION
+FIRMWARE_APPS_VERSION=$(tar Oxvf ${ATLASROOT} ./home/atlas/state/FIRMWARE_APPS_VERSION)
 LOC_ROOTFS_FILE_BASE="turrisos-5.2.7-9882a54c4848e2e282bca435c6aa0025d9fa37df-mvebu-cortexa53-device-ripe-atlas-rootfs.tar"
+ROOTFS_VERSION="$FIRMWARE_APPS_VERSION"
+ROOTFS_FILE="rootfs-$model-$ROOTFS_VERSION.img.bz2"
 LOC_ROOTFS_FILE_GZ="$LOC_ROOTFS_FILE_BASE".gz
 LOC_ROOTFS_FILE_BZ2="$LOC_ROOTFS_FILE_GZ".bz2
 
 # The Atlas backend wants bzip2, but schnapps only takes .gz
 bzip2 -c <"$BINDIR/$LOC_ROOTFS_FILE_GZ" >"$BINDIR/$LOC_ROOTFS_FILE_BZ2"
 
-FIRMWARE_APPS_VERSION=$(get_version)
-ROOTFS_VERSION="$FIRMWARE_APPS_VERSION"
-ROOTFS_FILE="rootfs-$model-$ROOTFS_VERSION.img.bz2"
-OPENSSL=openssl
-BASE64=base64
 
 if [ $probe_env = "prod" ] ; then
 	PREF=""
@@ -58,6 +80,15 @@ fi
 
 #exit
 
-scp "$BINDIR/$LOC_ROOTFS_FILE_BZ2" atlas@admin$PREF:$ROOTFS_FILE
+scp "$BINDIR/$LOC_ROOTFS_FILE_BZ2" atlas@admin$PREF:$ROOTFS_FILE >/dev/null 2>&1
+copyres=$?
+if [ $copyres -ne 0 ]; then
+	echo "Cannot automatically install firmware on atlas@admin$PREF. Please:"
+	echo "- Copy $BINDIR/$LOC_ROOTFS_FILE_BZ2 to atlas@admin$PREF:$ROOTFS_FILE"
+	echo -n "- Execute on atlas@admin$PREF "
+fi
+
 printf  "./atlas/manage.py import_app -a $model -w $ROOTFS_VERSION -g md5 -f ./$ROOTFS_FILE $sigarg\n"
-ssh atlas@admin$PREF "./atlas/manage.py import_app -a $model -w $ROOTFS_VERSION -g md5 -f ./$ROOTFS_FILE $sigarg"
+if [ $copyres -eq 0 ]; then
+	ssh atlas@admin$PREF "./atlas/manage.py import_app -a $model -w $ROOTFS_VERSION -g md5 -f ./$ROOTFS_FILE $sigarg"
+fi
